version: "3.9"

services:
  app:
    build: .
    container_name: myapp
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - SSL_KEY_PATH=${SSL_KEY_PATH}
      - SSL_CERT_PATH=${SSL_CERT_PATH}
      - AUDIO_FILE_DIRECTORY=${AUDIO_FILE_DIRECTORY}
      - AUDIO_FILE_NAME=${AUDIO_FILE_NAME}
      - LM_DIRECTORY=${LM_DIRECTORY}
      - TEMPLATES_DIRECTORY=${TEMPLATES_DIRECTORY}
      - SQLALCHEMY_DATABASE_URL=${SQLALCHEMY_DATABASE_URL}